In [1]:
import numpy as np
from sklearn.datasets import load_iris
from random import random
import math
import operator

In [2]:
df = load_iris()
df.data.shape

(150, 4)

In [3]:
def divide_data(x):
    for i in df.data:
        if random() < x:
            train_data.append(i)
        else:
            test_data.append(i)

In [4]:
def distance(x, y):#euclidean distance
    dist = 0
    for i in range(x.shape[0]):
        dist += math.pow(x[i] - y[i], 2)
    return math.sqrt(dist)

In [5]:
def mean_sum(arr): #mean sum to calculate value after we select k nearest neighbors
    sum_ = 0
    for i in arr:
           sum_+=i[feature_val]
    return sum_/len(arr)

In [6]:
def predict(arr, k):
    dist_arr = []
    mean_val = mean_sum(train_data)
    arr[feature_val] = mean_val
    #before calculating the distance we change the feature we calculate to a mean sum of the same feature in training set
    for i in train_data:
        dist_arr.append((i, distance(i, arr))) #dictionary to temporarily store object and distance to it
    dist_arr.sort(key=operator.itemgetter(1))#sort by distance
    nn = [] #array of nearest neighbors
    for j in range(k):
        nn.append(dist_arr[j][0]) 
    arr[feature_val] = mean_sum(nn) #rewrite calculated value 
    print(arr)

In [7]:
train_data = []
test_data = []
feature_val = 0
divide_data(0.90)
for i in test_data:
    print(i)
    predict(i, 7)
    print("----------")

[4.4 2.9 1.4 0.2]
[5.18571429 2.9        1.4        0.2       ]
----------
[4.8 3.  1.4 0.1]
[5.18571429 3.         1.4        0.1       ]
----------
[5.7 3.8 1.7 0.3]
[5.45714286 3.8        1.7        0.3       ]
----------
[5.4 3.4 1.5 0.4]
[5.32857143 3.4        1.5        0.4       ]
----------
[5.5 3.5 1.3 0.2]
[5.38571429 3.5        1.3        0.2       ]
----------
[4.4 3.2 1.3 0.2]
[5.24285714 3.2        1.3        0.2       ]
----------
[5.7 2.8 4.5 1.3]
[5.88571429 2.8        4.5        1.3       ]
----------
[6.  2.2 4.  1. ]
[5.62857143 2.2        4.         1.        ]
----------
[6.1 2.8 4.  1.3]
[5.7 2.8 4.  1.3]
----------
[6.8 2.8 4.8 1.4]
[5.98571429 2.8        4.8        1.4       ]
----------
[5.5 2.4 3.7 1. ]
[5.62857143 2.4        3.7        1.        ]
----------
[5.8 2.7 3.9 1.2]
[5.67142857 2.7        3.9        1.2       ]
----------
[6.  3.4 4.5 1.6]
[5.97142857 3.4        4.5        1.6       ]
----------
[6.5 3.  5.8 2.2]
[6.24285714 3.         5.8        2