In [1]:
import numpy as np
from sklearn.datasets import load_iris
from random import random
import math
import operator

In [2]:
df = load_iris()
df.data.shape

(150, 4)

In [3]:
def divide_data(x):
    for i in df.data:
        if random() < x:
            train_data.append(i)
        else:
            test_data.append(i)

In [4]:
def feature_erase(k): #don't use it because it's kinda pointless. I still calculate and rewrite value
    for i in test_data:
        i[k] = None

In [5]:
def distance(x, y):#euclidean distance
    dist = 0
    for i in range(x.shape[0]):
        dist += math.pow(x[i] - y[i], 2)
    return math.sqrt(dist)

In [6]:
def mean_sum(arr): #mean sum to calculate value after we select k nearest neighbors
    sum_ = 0
    for i in arr:
           sum_+=i[feature_val]
    return sum_/len(arr)

In [7]:
def predict(arr, k):
    dist_arr = []
    for i in train_data:
        dist_arr.append((i, distance(i, arr))) #dictionary to temporarily store object and distance to it
    dist_arr.sort(key=operator.itemgetter(1))
    nn = [] #array of nearest neighbors
    for j in range(k):
        nn.append(dist_arr[j][0]) 
    arr[feature_val] = mean_sum(nn) #rewrite calculated value 
    print(arr)

In [8]:
train_data = []
test_data = []
feature_val = 0
divide_data(0.90)
#feature_erase(0)
print("first row - real data, second is predicted. By default predicts 1 feature of an object")
for i in test_data:
    print(i)
    predict(i, 7)
    print("----------")

first row - real data, second is predicted. By default predicts 1 feature of an object
[4.9 3.  1.4 0.2]
[4.84285714 3.         1.4        0.2       ]
----------
[5.  3.4 1.5 0.2]
[5.02857143 3.4        1.5        0.2       ]
----------
[5.7 3.8 1.7 0.3]
[5.4 3.8 1.7 0.3]
----------
[4.9 3.1 1.5 0.1]
[4.87142857 3.1        1.5        0.1       ]
----------
[5.  3.2 1.2 0.2]
[4.9 3.2 1.2 0.2]
----------
[5.1 3.4 1.5 0.2]
[5.08571429 3.4        1.5        0.2       ]
----------
[5.  3.5 1.3 0.3]
[5.1 3.5 1.3 0.3]
----------
[6.4 3.2 4.5 1.5]
[6.41428571 3.2        4.5        1.5       ]
----------
[6.3 3.3 4.7 1.6]
[6.12857143 3.3        4.7        1.6       ]
----------
[4.9 2.4 3.3 1. ]
[5.37142857 2.4        3.3        1.        ]
----------
[5.  2.  3.5 1. ]
[5.38571429 2.         3.5        1.        ]
----------
[6.7 3.1 4.4 1.4]
[6.65714286 3.1        4.4        1.4       ]
----------
[5.6 3.  4.1 1.3]
[5.71428571 3.         4.1        1.3       ]
----------
[6.8 3.  5.5 2.1]
[6.6